name: Node.js CI

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    outputs:
      coveralls: ${{ steps.changes.outputs.src }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: |
        npm ci
        npm run build
        if [ "${{ runner.os }}" == "Windows" ]; then
          npm test
        else
          xvfb-run --auto-servernum npm test
        fi
      shell: bash
